export class User {
  constructor(public _id?: string,
              public profPic?: string,
              public coverPic?: string,
              public _profilePhoto?:{ fileName:string},
              public _coverPhoto?:{fileName:string},
              public firstName?: string,
              public userType?: string,
              public lastName?: string,
              public username?: string,
              public phone?: string,
              public dateOfBirth?: string,
              public country?: string,
              public state?: string,
              public city?: string,
              public email?: string,
              public summary?: string,
              public objective?: string,
              public functionalAreas?: string,
              public industries?: string,
              public password?: string,
              public userProfilePic?: { name: string },
              public userCoverPic?: { name: string },
              public profileVisibility?: string,
              public profileStatus?: string,
              public twoWayAutEnabled?: boolean,
              public oldPassword?: string,
              public confirmPassword?: string,
              public emailVerified?: boolean
  ) {}
}